eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true      # safer across Docker/hosts
    # optional but helpful if you run behind NAT/containers:
    # ip-address: ${HOST_IP:}    # set via env if needed
    
microservices:
  payment-service:
    endpoints:
      doPayment:
        uri: lb://payment-service/payment/doPayment
  order-service:
    endpoints:
      bookOrder:
        uri: lb://order-service/order/bookOrder
