eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
microservices:
  payment-service:
    endpoints:
      doPayment:
        uri: http://PAYMENT-SERVICE/payment/doPayment
  order-service:
    endpoints:
      bookOrder:
        uri: http://ORDER-SERVICE/payment/bookOrder
