# request tracing props
management:
  tracing:
    sampling:
      probability: 1.0    # 100% sample for local testing; lower in prod (e.g., 0.05)
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans  # Zipkin’s default

logging:
  pattern:
    # Include trace + span IDs in logs (works with Logback)
    level: "%5p [${spring.application.name:unknown},traceId=%X{traceId:-},spanId=%X{spanId:-}] %m%n"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true      # safer across Docker/hosts
    # optional but helpful if you run behind NAT/containers:
    # ip-address: ${HOST_IP:}    # set via env if needed
    
microservices:
  payment-service:
    endpoints:
      doPayment:
        uri: lb://payment-service/payment/doPayment
  order-service:
    endpoints:
      bookOrder:
        uri: lb://order-service/order/bookOrder
